// packages/react-rx-store-example-counter/src/Counter.tsx
import React from "react";
import { useRxStore, useSubscription } from "@rx-store/react-rx-store";
import { AppContextValue } from "./types";

function Counter() {
  const store = useRxStore<AppContextValue>();

  const [count] = useSubscription(store.count$);
  const [localCount] = useSubscription(store.localCount$);

  return (
    <div className="App">
      <h1> Counter</h1>
      count: {count}
      local: {localCount}
      <button onClick={() => store.counterChange$.next(1)}>add</button>
      <button onClick={() => store.counterChange$.next(-1)}>subtract</button>
    </div>
  );
}

export default Counter;

// apps/angular-example-counter/src/app/counter/counter.component.ts
import { Component, Input } from '@angular/core';
import { RootAppStore } from '../types';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  styleUrls: ['./counter.component.scss']
})
export class CounterComponent {

  @Input() store: RootAppStore;

}

<div class="App">
  <h1>Counter</h1>

  <div>count: {{ storeManager?.store.count$ | async }}</div>
  <div>local: {{ localCount$ | async }}</div>

  <button (click)="storeManager.store.counterChange$.next(1)">add</button>
  <button (click)="storeManager.store.counterChange$.next(-1)">subtract</button>
</div>
