// apps/react-example-counter/src/app/Counter.tsx
import React, { useMemo } from 'react';
import { useSubscription, useStore } from '@rx-store/react-rx-store';
import { rootContext } from './Manager';
import { scanSum } from './store/operators/scan-sum';

function Counter() {
  const store = useStore(rootContext);

  const [count] = useSubscription(store.count$);

  const localCount$ = useMemo(() => store.counterChange$.pipe(scanSum()), [
    store.counterChange$,
  ]);
  const [localCount] = useSubscription(localCount$);

  return (
    <div className="App">
      <h1> Counter</h1>
      count: {count}
      local: {localCount}
      <button onClick={() => store.counterChange$.next(1)}>add</button>
      <button onClick={() => store.counterChange$.next(-1)}>subtract</button>
    </div>
  );
}

export default Counter;

// apps/angular-example-counter/src/app/counter/counter.component.ts
import { Component, Input } from '@angular/core';
import { AppStoreValue } from '../types';
import { StoreManagerService } from '../store/store-manager.service';
import { scanSum } from '../store/operators/scan-sum';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  styleUrls: ['./counter.component.scss']
})
export class CounterComponent {
  localCount$ = this.storeManager.store.counterChange$.pipe(scanSum());
  constructor(public readonly storeManager: StoreManagerService) {
  }

}

<div class="App">
  <h1>Counter</h1>

  <div>count: {{ storeManager?.store.count$ | async }}</div>
  <div>local: {{ localCount$ | async }}</div>

  <button (click)="storeManager.store.counterChange$.next(1)">add</button>
  <button (click)="storeManager.store.counterChange$.next(-1)">subtract</button>
</div>
